### PR TITLE
Fix test failures in t/pod.t

### PR DESCRIPTION
**Pull request by chromatic**
The culprit was a spurious Unicode space.

### CODE REVIEW

**Comment by tokuhirom** [comment]
+1

**Comment by tokuhirom** [comment]
And move this test to xt/ is more better.

**Comment by rjbs** [comment]
I am also hoping to see this merged and released!

**Comment by rsrchboy** [comment]
+1 -- very frustrating :)

**Comment by sukria** [comment]
Going to merge that soon! Thanks :)

**Comment by rjbs** [comment]
I should've also noted that I also agree that pod.t should not be running for every user installing the library.  Better to only run if AUTHOR_TESTING is set to put the test in xt, or something like that.

Anyway, thanks!

**Pull request merged**
