### PR TITLE
adding support for multiple methods

### PR DESCRIPTION
**Pull request by xsawyerx**
hey

i wanted to be able to write less code by doing:
    mock 'This::Class'
        => methods ['this', 'that']
        => should { ... };

instead of writing the mocking twice, i added an arrayref option to it and syntactic sugar called "methods" (defined exactly the same way) to allow for this.

i also want to refactor some of the code, so i might do that later.

### CODE REVIEW

**Comment by xsawyerx** [comment]
Whoops! Forgot to add the test files (two of them) to MANIFEST.

You'll have to add them to MANIFEST.

**Comment by sukria** [comment]
pulling and reviewing, thanks for the patch :)

**Comment by sukria** [comment]
hmm, looks like the pull broke the test suite:

$ make test
[...]
Failed 3/10 test programs. 4/49 subtests failed.

Can you check that?

**Comment by xsawyerx** [comment]
I see the problem: it's with a typo correction I've made.

**Comment by xsawyerx** [comment]
Made two commits that fix this and add the missing files to MANIFEST! :)

**Pull request merged**
